project:
  type: website

website:
  title: "Hemimastix"
  description: A protist attempting to code
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - href: about.qmd
        text: About
      #- href: research.qmd  # restore this
      #  text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: "Resources"
      - href: gallery.qmd
        text: Protist gallery
  page-footer:
    # is this a comment   "Protistology\n resources"
    left: |
      Yana Eglit 2026 | This work is licensed under CC BY-NC-SA 4.0 unless specified otherwise.
      This site was made in Quarto using the Lux theme. Written and coded without AI.

format:
  html:
    theme: lux
    css: styles.css
    toc: true



#<!-- original theme: lux -->
