---
title: "The world of *Hemimastix*<br>(and Yana Eglit)"
---

## What is a protist?

**Protists** are the rest of eukaryotes^[organisms with nucleated cells, or, very loosely and not correctly, 'not-bacteria'] outside the classical
kingdoms Animals, Fungi, and Land Plants. Most (but far from all) protists are unicellular and microscopic, and
represent the greatest range of cellular complexity -- from giant intricate shell-building amoebae in the ocean to
exceptionally reduced intracellular parasites. They include algae of many colours that play a fundamental role in
marine and aquatic ecosystems to eukaryotrophs, or eukaryotes that prey upon other eukaryotes, whose identities and
ecological contributions remain so poorly studied we cannot comment much on them. Most eukaryotes, including the last
common ancestor of all modern eukaryotes (**"LECA"**), rely on oxygenic respiration for energy production ("mitochondria
are the powerhouse of the cell"); however, protist groups have repeatedly adapted to an oxygen-free lifestyle accompanied
by sometimes very dramatic reductions of the mitochondrion -- in some cases *importing* ATP into the organelle ("mitochondria
are not always the powerhouse of the cell, and perform other roles"). Free-living protists, especially those in sediments,
especially those in anoxic habitats, especially flagellates, especially those that require other protists to live
(as symbiosis or food) are some of the most little-studied organisms in all of biology.

Several colleagues and I use classical low-throughput methods like examining samples and their enrichments on a light microscope to identify
poorly-characterised or unknown protists and attempt to 'domesticate' them as laboratory **cultures**. This general approach,
despite being in use for several centuries, continues to yield more exciting discoveries than our small field can frankly
handle. Like space and the deep sea, microbiology remains one of our final great frontiers. Unlike space and the deep sea,
microbiology only requires decent optics to access, and this alien world is right at our feet. Sometimes literally:
I was lucky to find and isolate an enigmatic eukaryotroph *Hemimastix kukwesjijk* from
[some soil collected on a local hike](https://communities.springernature.com/posts/microbes-underfoot-yield-a-new-major-lineage-of-eukaryotes),
and even luckier to collaborate with fantastic experts on single cell molecular techniques and **phylogenomics** to discover that
this group of strange protists, whose taxonomic identity was elusive for over a century, turned out to represent a distinct
[deep-branching eukaryotic lineage in its own right](https://doi.org/10.1038/s41586-018-0708-8); furthermore,
in the following years it turned out the be the first representative of what is now an emerging *bona fide* [supergroup of eukaryotes](https://doi.org/10.1038/s41586-025-09750-0).
A swath of microbial diversity was largely unknown until recently, and this kind of story will not be the last.

If we are missing entire supergroups of the tree of eukaryotes, how can we fully understand the microbial fraction of our
ecosystems, a fraction in every way as complex as the interactions among the flora and fauna you can see around you on a
forest walk? Gathering molecular sequence data improves reference databases for [molecular] microbial ecologists to accurately
identify their sequenced taxa. Studying the cell biology and biochemistry of these organisms can not only expose clues to
their roles in an ecological context, but also put our understanding of cell biological and biochemical "rules" to a harsh test.
Protists present an impressive inventory of elaborate cellular structures from [camera eyes](https://doi.org/10.1038/nature14593)
and [tiny guns](https://doi.org/10.1126/sciadv.1602552) to [glass-crafting](https://diatoms.org/) and [basket-weaving](https://www.sciencedirect.com/science/article/abs/pii/S1434461007000776). One member of Ameobozoa of all groups
has the first [rotary flagellum](https://doi.org/10.1038/s41564-019-0478-6) known in a eukaryote^[a hallmark of a structurally- and evolutionarily-unrelated prokaryotic flagellum],
altogether representing thus far the only known case of a "toroidal swimmer" predicted by [theoretical physics](https://doi.org/10.1119/1.10903) [pdf](https://www.damtp.cam.ac.uk/user/gold/pdfs/purcell.pdf).
Or what can we learn about cytoskeleton biology from this [remarkable protist with arm-like protrusions](https://doi.org/10.1016/j.cub.2023.12.032)
that swing to and fro as it glides?

Scientific value aside, protists are weird and fascinating and *beautiful*. I try my best to capture some aspect of this using microscopy.

Note: Individuals of all known *Hemimastix* species remain unaware of the author's existence. But they also can't complain
about being appropriated for a personal website, on account of being too small to lick a postage stamp.

[**About me**](/about.qmd)

[**About *Hemimastix***](https://www.quantamagazine.org/what-a-newfound-kingdom-means-for-the-tree-of-life-20181211/)

[**Gallery of protist-themed microscopy and artwork**](/gallery.qmd)

[International Society of Protistologists](https://protistologists.org/)
